
package fr.afcepf.al28.ticketshack.bpel;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "processTicketsHackPortType", targetNamespace = "http://bpel.ticketshack.al28.afcepf.fr")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    fr.afcepf.al28.ticketshack.bpel.ObjectFactory.class,
    fr.afcepf.al28.webservice.soap.ObjectFactory.class,
    fr.toto.ObjectFactory.class
})
public interface ProcessTicketsHackPortType {


    /**
     * 
     * @param payload
     * @return
     *     returns fr.afcepf.al28.ticketshack.bpel.ProcessTicketsHackResponse
     */
    @WebMethod(action = "http://bpel.ticketshack.al28.afcepf.fr/process")
    @WebResult(name = "processTicketsHackResponse", targetNamespace = "http://bpel.ticketshack.al28.afcepf.fr", partName = "payload")
    public ProcessTicketsHackResponse process(
        @WebParam(name = "processTicketsHackRequest", targetNamespace = "http://bpel.ticketshack.al28.afcepf.fr", partName = "payload")
        ProcessTicketsHackRequest payload);

}
